sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.organization=${env.SONAR_ORGANIZATION}
sonar.projectName=Microservice-Springboot-Angular

# Répertoire à analyser
sonar.sources=src

# Inclusions spécifiques au module
sonar.inclusions=src/**

# Langage
sonar.language=java
sonar.sourceEncoding=UTF-8
